/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JCodeRouteImport } from './routes/j.$code'
import { Route as ApiPublicLinkRouteImport } from './routes/api/public/link'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JCodeRoute = JCodeRouteImport.update({
  id: '/j/$code',
  path: '/j/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkRoute = ApiPublicLinkRouteImport.update({
  id: '/api/public/link',
  path: '/api/public/link',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/j/$code': typeof JCodeRoute
  '/api/public/link': typeof ApiPublicLinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/j/$code': typeof JCodeRoute
  '/api/public/link': typeof ApiPublicLinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/j/$code': typeof JCodeRoute
  '/api/public/link': typeof ApiPublicLinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/j/$code' | '/api/public/link'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/j/$code' | '/api/public/link'
  id: '__root__' | '/' | '/j/$code' | '/api/public/link'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JCodeRoute: typeof JCodeRoute
  ApiPublicLinkRoute: typeof ApiPublicLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/j/$code': {
      id: '/j/$code'
      path: '/j/$code'
      fullPath: '/j/$code'
      preLoaderRoute: typeof JCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/link': {
      id: '/api/public/link'
      path: '/api/public/link'
      fullPath: '/api/public/link'
      preLoaderRoute: typeof ApiPublicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JCodeRoute: JCodeRoute,
  ApiPublicLinkRoute: ApiPublicLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
